AWSTemplateFormatVersion: 2010-09-09
Description: This template Create Subnet Group Parameter Group and Option Group For RDS.
# Metadata: 

Parameters: 
  EnviromentName:
    Type: String
    Default: Development
    Description: Environment Name that will be used to name resources. 
  
  NetworkstackName:
    Type: String
    Default: DevelopmentVPC
    Description: Network Stack Name that will be used to name resources.

# Mappings: 

# Conditions: 

Resources: 
  DevelopmentDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: This Subnet Group is used for Development RDS.
      DBSubnetGroupName: DevelopmentDBSubnetGroup
      SubnetIds:
        - Fn::ImportValue:
            'Fn::Sub': '${NetworkstackName}-PRIVSUBEPA'
        - Fn::ImportValue:
            'Fn::Sub': '${NetworkstackName}-PRIVSUBEPB'
        - Fn::ImportValue:
            'Fn::Sub': '${NetworkstackName}-PRIVSUBEPC' 
      Tags:
      - Key: Name
        Value: DevelopmentDBSubnetGroup

  DevelopmentDBOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      OptionGroupName: DevelopmentOptionGroup
      OptionGroupDescription: This Option Group is used for Development RDS.
      EngineName: mysql
      MajorEngineVersion: 5.7

  DevelopmentDBOptionGroup8:
    Type: AWS::RDS::OptionGroup
    Properties:
      OptionGroupName: DevelopmentOptionGroup8
      OptionGroupDescription: This Option Group is used for Development RDS with Mysql 8.
      EngineName: mysql
      MajorEngineVersion: 8.0
  
  DevelopmentDBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: DevelopmentDBParameterGroup
      Description: This Parameter Group is used for Development RDS.
      Family: mysql5.7
      Parameters:
        connect_timeout: 31536000
        delayed_insert_timeout: 31535000
        event_scheduler: "ON"
        general_log: 1
        group_concat_max_len: 500000
        innodb_buffer_pool_instances: 8
        innodb_file_per_table: 0
        innodb_flush_log_at_trx_commit: 1
        innodb_lock_wait_timeout: 1073641824
        innodb_log_file_size: 3221225472
        innodb_print_all_deadlocks: 1
        innodb_strict_mode: 0
        innodb_support_xa: 1
        innodb_thread_concurrency: 150
        interactive_timeout: 400
        join_buffer_size: 268435456
        lock_wait_timeout: 31535000
        log_bin_trust_function_creators: 1
        log_output: FILE
        log_queries_not_using_indexes: 0
        long_query_time: 0.7
        max_allowed_packet: 1073741824
        max_connect_errors: 100000
        max_connections: 90000
        max_execution_time: 600000
        max_user_connections: 50000
        performance_schema: 1
        query_cache_size: 200
        slow_query_log: 1
        sort_buffer_size: 268435456
        sql_mode: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        table_definition_cache: 10000
        table_open_cache: 10000
        time_zone: "Asia/Calcutta"
        tx_isolation: "READ-COMMITTED"
        wait_timeout: 600
      Tags:
        - Key: Name
          Value: DevelopmentDBParameterGroup

  DevelopmentDBParameterGroup8:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: DevelopmentDBParameterGroup8
      Description: This Parameter Group is used for Development RDS For Mysql 8.
      Family: mysql8.0
      Parameters:
        connect_timeout: 31536000
        delayed_insert_timeout: 31535000
        event_scheduler: "ON"
        general_log: 1
        group_concat_max_len: 500000
        innodb_buffer_pool_instances: 8
        innodb_file_per_table: 0
        innodb_flush_log_at_trx_commit: 1
        innodb_lock_wait_timeout: 1073641824
        innodb_log_file_size: 3221225472
        innodb_print_all_deadlocks: 1
        innodb_strict_mode: 0
        innodb_thread_concurrency: 150
        interactive_timeout: 400
        join_buffer_size: 268435456
        lock_wait_timeout: 31535000
        log_bin_trust_function_creators: 1
        log_output: FILE
        log_queries_not_using_indexes: 0
        long_query_time: 0.7
        max_allowed_packet: 1073741824
        max_connect_errors: 100000
        max_connections: 90000
        max_execution_time: 600000
        max_user_connections: 50000
        performance_schema: 1
        slow_query_log: 1
        sort_buffer_size: 268435456
        sql_mode: "ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PAD_CHAR_TO_FULL_LENGTH,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,ANSI,TRADITIONAL"
        table_definition_cache: 10000
        table_open_cache: 10000
        time_zone: "Asia/Calcutta"
        wait_timeout: 600
        transaction_isolation: "READ-COMMITTED"
      Tags:
        - Key: Name
          Value: DevelopmentDBParameterGroup8

  

Outputs:
  DevelopmentDBSubnetGroup:
    Description: DevelopmentDBSubnetGroup
    Value: !Ref DevelopmentDBSubnetGroup
    Export: 
      Name: !Sub '${AWS::StackName}-DevelopmentDBSubnetGroup'

  DevelopmentDBOptionGroup:
    Description: DevelopmentDBOptionGroup
    Value: !Ref DevelopmentDBOptionGroup
    Export: 
      Name: !Sub '${AWS::StackName}-DevelopmentDBOptionGroup'

  DevelopmentDBParameterGroup:
    Description: DevelopmentDBParameterGroup
    Value: !Ref DevelopmentDBParameterGroup
    Export: 
      Name: !Sub '${AWS::StackName}-DevelopmentDBParameterGroup'

  DevelopmentDBOptionGroup8:
    Description: DevelopmentDBOptionGroup8
    Value: !Ref DevelopmentDBOptionGroup8
    Export: 
      Name: !Sub '${AWS::StackName}-DevelopmentDBOptionGroup8'

  DevelopmentDBParameterGroup8:
    Description: DevelopmentDBParameterGroup8
    Value: !Ref DevelopmentDBParameterGroup8
    Export: 
      Name: !Sub '${AWS::StackName}-DevelopmentDBParameterGroup8'